#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2024-2026 The XTC Project Authors
#
from .operations import register_operation

__all__ = []

# generated by MetaScheduleEval/xtc_conversion/gen_probsizes.py
squeezenet_convs = {
        'squeezenetconv_0': {'n': 1, 'h': 224, 'w': 224, 'c': 3, 'r': 7, 's': 7, 'f': 96, 'strx': 2, 'stry': 2}, 
        'squeezenetconv_1': {'n': 1, 'h': 54, 'w': 54, 'c': 96, 'r': 1, 's': 1, 'f': 16, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_2': {'n': 1, 'h': 54, 'w': 54, 'c': 16, 'r': 1, 's': 1, 'f': 64, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_3': {'n': 1, 'h': 56, 'w': 56, 'c': 16, 'r': 3, 's': 3, 'f': 64, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_4': {'n': 1, 'h': 54, 'w': 54, 'c': 128, 'r': 1, 's': 1, 'f': 16, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_5': {'n': 1, 'h': 54, 'w': 54, 'c': 128, 'r': 1, 's': 1, 'f': 32, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_6': {'n': 1, 'h': 56, 'w': 56, 'c': 32, 'r': 1, 's': 1, 'f': 128, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_7': {'n': 1, 'h': 54, 'w': 54, 'c': 32, 'r': 3, 's': 3, 'f': 128, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_8': {'n': 1, 'h': 27, 'w': 27, 'c': 256, 'r': 1, 's': 1, 'f': 32, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_9': {'n': 1, 'h': 29, 'w': 29, 'c': 32, 'r': 1, 's': 1, 'f': 128, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_10': {'n': 1, 'h': 27, 'w': 27, 'c': 32, 'r': 3, 's': 3, 'f': 128, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_11': {'n': 1, 'h': 27, 'w': 27, 'c': 256, 'r': 1, 's': 1, 'f': 48, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_12': {'n': 1, 'h': 29, 'w': 29, 'c': 48, 'r': 1, 's': 1, 'f': 192, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_13': {'n': 1, 'h': 27, 'w': 27, 'c': 48, 'r': 3, 's': 3, 'f': 192, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_14': {'n': 1, 'h': 27, 'w': 27, 'c': 384, 'r': 1, 's': 1, 'f': 48, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_15': {'n': 1, 'h': 29, 'w': 29, 'c': 384, 'r': 1, 's': 1, 'f': 64, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_16': {'n': 1, 'h': 27, 'w': 27, 'c': 64, 'r': 1, 's': 1, 'f': 256, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_17': {'n': 1, 'h': 27, 'w': 27, 'c': 64, 'r': 3, 's': 3, 'f': 256, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_18': {'n': 1, 'h': 15, 'w': 15, 'c': 512, 'r': 1, 's': 1, 'f': 64, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_19': {'n': 1, 'h': 13, 'w': 13, 'c': 64, 'r': 1, 's': 1, 'f': 256, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_20': {'n': 1, 'h': 13, 'w': 13, 'c': 64, 'r': 3, 's': 3, 'f': 256, 'strx': 1, 'stry': 1}, 
        'squeezenetconv_21': {'n': 1, 'h': 15, 'w': 15, 'c': 512, 'r': 1, 's': 1, 'f': 1000, 'strx': 1, 'stry': 1}
}

alexnet_convs = {
        'alexnetconv_0': {'n': 1, 'h': 228, 'w': 228, 'c': 3, 'r': 11, 's': 11, 'f': 64, 'strx': 4, 'stry': 4}, 
        'alexnetconv_1': {'n': 1, 'h': 31, 'w': 31, 'c': 64, 'r': 5, 's': 5, 'f': 192, 'strx': 1, 'stry': 1}, 
        'alexnetconv_2': {'n': 1, 'h': 15, 'w': 15, 'c': 192, 'r': 3, 's': 3, 'f': 384, 'strx': 1, 'stry': 1}, 
        'alexnetconv_3': {'n': 1, 'h': 15, 'w': 15, 'c': 384, 'r': 3, 's': 3, 'f': 256, 'strx': 1, 'stry': 1}, 
        'alexnetconv_4': {'n': 1, 'h': 15, 'w': 15, 'c': 256, 'r': 3, 's': 3, 'f': 256, 'strx': 1, 'stry': 1}
}
alexnet_matmuls = {
        'alexnetmatmul_0': {'i': 1, 'j': 4096, 'k': 9216}, 
        'alexnetmatmul_1': {'i': 1, 'j': 4096, 'k': 4096}, 
        'alexnetmatmul_2': {'i': 1, 'j': 1000, 'k': 4096}
}


# loop-explore --operator conv2d --ops-list

def _register_conv2d_ops():
    for group in [squeezenet_convs, alexnet_convs]:
        for name, params in group.items():
            register_operation(
                "conv2d",
                name,
                {k: params[k] for k in ["n", "h", "w", "f", "r", "s", "c"]},
                {"SH": params["stry"], "SW": params["strx"]},
            )


def _register_matmul_ops():
    for group in [alexnet_matmuls]:
        for name, params in group.items():
            register_operation(
                "matmul",
                name,
                {k: params[k] for k in ["i", "j", "k"]},
            )


def _register_operations():
    _register_conv2d_ops()
    _register_matmul_ops()
